import React from "react";

interface CoverPageProps {
  userName: string;
  generationDate: string;
  filters: {
    zone: string;
    gender: string;
    travelType: string;
    destination: string;
  };
}

const ReportCoverPage: React.FC<CoverPageProps> = ({
  userName,
  generationDate,
  filters,
}) => {
  return (
    <div
      className="bg-white p-12 border mx-auto my-8 shadow-xl"
      style={{ width: "794px", height: "1123px" }} // A4 size at 96 DPI
    >
      <div className="flex flex-col justify-between h-full">
        {/* Top Logo and Title */}
        <div className="text-center mt-20">
          <h1 className="text-4xl font-extrabold text-green-800 uppercase tracking-wide mb-2">
            Vaccination Report
          </h1>
          <p className="text-xl font-medium text-gray-700 mt-4">
            FINANCE SUPER ADMIN REPORT
          </p>
        </div>

        {/* Filters Summary */}
        <div className="mt-24 text-lg text-gray-800 leading-relaxed">
          <h2 className="text-2xl font-semibold text-green-700 mb-6 underline">
            Report Filters Summary
          </h2>
          <p>
            <span className="font-bold">Zone:</span> {filters.zone}
          </p>
          <p>
            <span className="font-bold">Gender:</span> {filters.gender}
          </p>
          <p>
            <span className="font-bold">Travel Type:</span> {filters.travelType}
          </p>
          <p>
            <span className="font-bold">Destination:</span>{" "}
            {filters.destination}
          </p>
        </div>

        {/* Generated By Section */}
        <div className="mt-auto mb-10">
          <p className="text-gray-700 text-lg">
            <span className="font-semibold">Generated by:</span> FINANCE SUPER ADMIN
          </p>
          <p className="text-gray-700 text-lg">
            <span className="font-semibold">Date of Generation:</span>{" "}
            {generationDate}
          </p>
        </div>

        {/* Footer */}
        <footer className="text-center border-t pt-6 text-sm text-gray-500">
          Finance Super Admin Reporting System &mdash; Confidential
        </footer>
      </div>
    </div>
  );
};

export default ReportCoverPage;
